eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    service-url:
      defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka

spring:
  data:
    mongodb:
      #uri: mongodb+srv://admin:codedecode@atlas-cluster.mqdj7js.mongodb.net/?retryWrites=true&w=majority # mongodb://localhost:27017/orderdb
      uri: mongodb+srv://admin:Pass1234@atlas-cluster.yxh16pi.mongodb.net/?retryWrites=true&w=majority
      #host: atlas-cluster.mqdj7js.mongodb.net
      host: atlas-cluster.yxh16pi.mongodb.net
      port: 27017
      database: orderdb
      repositories:
        enabled: true 